# https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
# https://github.com/saltchess/arcaea-wiki-sometry/actions/workflows/trigger.yml
# https://nodejs.org/api/fs.html
# http://www.ruanyifeng.com/blog/2019/12/github_actions.html
# https://stackoverflow.com/questions/68521765/how-to-cache-npm-dependencies-in-github-action
# https://github.com/actions/setup-node#caching-global-packages-data
# https://github.com/jtmullen/mediawiki-edit-action
# https://wiki.arcaea.cn/Special:%E7%94%A8%E6%88%B7%E8%B4%A1%E7%8C%AE/GuBot
name: arcaea-wiki-sometry

on:
  # schedule:
  #   - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ env.URL }}
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 7.14.2
    - uses: actions/setup-node@v3
      with:
        node-version: '16.15'
        cache: 'pnpm'
    - run: pnpm i
    - run: |
        read -a ARR < <(node ./js/check-update.js 0 | xargs)
        echo "URL=${ARR[0]}" >> $GITHUB_ENV
        rawText="$( printf "\n%s" "${ARR[@]:2}" )"
        echo 'TEXT<<EOF' >> $GITHUB_ENV
        echo "${rawText:1}" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        echo $rawText
    - run: |
        echo ${{ env.URL }}
        echo "${{ env.TEXT }}"
    - uses: jtmullen/mediawiki-edit-action@v0
      with:
        wiki_text: "${{ env.TEXT }}"
        edit_summary: "Powered By Github Action"
        # page_name: "Template:version"
        page_name: "User:盐棋/Sandbox1"
        api_url: "https://wiki.arcaea.cn/api.php"
        username: "${{ secrets.WIKI_USERNAME }}"
        password: ${{ secrets.WIKI_PASSWORD }}
        minor: true
  # download-apk:
  #   runs-on: ubuntu-latest
  #   needs: check-update
  #   steps:
  #   - run: sudo apt-get install -y aria2
  #   - run: aria2c ${{ needs.check-update.outputs.url }} -j 32 -c -o base.apk
  #   - run: unzip ./base.apk -d ./base
  #   - uses: actions/cache@v3
  #     with:
  #       path: |
  #         ./base/assets/songs/
  #         !./base/assets/songs/*/
  #       key: ${{ runner.os }}-my_file
  # edit-wikipage-1:
  #   needs: [check-update, download-apk]
  #   runs-on: ubuntu-latest
  #   env:
  #     SONGS: ./base/assets/songs
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/cache@v3
  #     with:
  #       path: |
  #         ./base/assets/songs/
  #         !./base/assets/songs/*/
  #       key: ${{ runner.os }}-my_file
  #   - uses: pnpm/action-setup@v2
  #     with:
  #       version: 7.14.2
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '16.15'
  #       cache: 'pnpm'
  #   - run: pnpm i
  #   - run: |
  #       RESULT=$(node ./js/check-edit.js ${{ env.SONGS }}/packlist)
  #       echo "RESULT=$RESULT" >> $GITHUB_ENV
  #   - if: ${{ env.RESULT }} == 'true'
  #     uses: jtmullen/mediawiki-edit-action@v0
  #     with:
  #       wiki_text_file: "${{ env.SONGS }}/packlist"
  #       edit_summary: "Powered By Github Action"
  #       page_name: "Template:packlist.json"
  #       api_url: "https://wiki.arcaea.cn/api.php"
  #       username: "${{ secrets.WIKI_USERNAME }}"
  #       password: ${{ secrets.WIKI_PASSWORD }}
  #       minor: true
  # edit-wikipage-2:
  #   needs: [check-update, download-apk]
  #   runs-on: ubuntu-latest
  #   env:
  #     SONGS: ./base/assets/songs
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/cache@v3
  #     with:
  #       path: |
  #         ./base/assets/songs/
  #         !./base/assets/songs/*/
  #       key: ${{ runner.os }}-my_file
  #   - uses: pnpm/action-setup@v2
  #     with:
  #       version: 7.14.2
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '16.15'
  #       cache: 'pnpm'
  #   - run: pnpm i
  #   - run: |
  #       RESULT=$(node ./js/check-edit.js ${{ env.SONGS }}/songlist)
  #       echo "RESULT=$RESULT" >> $GITHUB_ENV
  #   - if: ${{ env.RESULT }} == 'true'
  #     uses: jtmullen/mediawiki-edit-action@v0
  #     with:
  #       wiki_text_file: "${{ env.SONGS }}/songlist"
  #       edit_summary: "Powered By Github Action"
  #       page_name: "Template:songlist.json"
  #       api_url: "https://wiki.arcaea.cn/api.php"
  #       username: "${{ secrets.WIKI_USERNAME }}"
  #       password: ${{ secrets.WIKI_PASSWORD }}
  #       minor: true
  # edit-wikipage-3:
  #   needs: [check-update, download-apk]
  #   runs-on: ubuntu-latest
  #   env:
  #     SONGS: ./base/assets/songs
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/cache@v3
  #     with:
  #       path: |
  #         ./base/assets/songs/
  #         !./base/assets/songs/*/
  #       key: ${{ runner.os }}-my_file
  #   - uses: pnpm/action-setup@v2
  #     with:
  #       version: 7.14.2
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '16.15'
  #       cache: 'pnpm'
  #   - run: pnpm i
  #   - run: |
  #       RESULT=$(node ./js/check-edit.js ${{ env.SONGS }}/unlocks)
  #       echo "RESULT=$RESULT" >> $GITHUB_ENV
  #   - if: ${{ env.RESULT }} == 'true'
  #     uses: jtmullen/mediawiki-edit-action@v0
  #     with:
  #       wiki_text_file: "${{ env.SONGS }}/unlocks"
  #       edit_summary: "Powered By Github Action"
  #       page_name: "Template:unlocks.json"
  #       api_url: "https://wiki.arcaea.cn/api.php"
  #       username: "${{ secrets.WIKI_USERNAME }}"
  #       password: ${{ secrets.WIKI_PASSWORD }}
  #       minor: true