name: try

on:
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 7.14.2
    - uses: actions/setup-node@v3
      with:
        node-version: '16.15'
        cache: 'pnpm'
    - run: pnpm i
  download-apk:
    runs-on: ubuntu-latest
    needs: check-update
    steps:
    - run: sudo apt-get install -y aria2
    - run: aria2c https://static-bin.lowiro.com/serve/arcaea_4.1.3c.apk?token=3Ad7D3EXvx7K5l4ZzS9Vc5sv8LxfKqEj7D7bBuYLXUoKQS1LNpKRdtwhNcQPNjmu9 -j 32 -c -o base.apk
    - run: unzip ./base.apk -d ./base
    - uses: actions/cache@v3
      with:
        path: |
          ./base/assets/songs/
          !./base/assets/songs/*/
        key: ${{ runner.os }}-my_file
  edit-wikipage:
    needs: [download-apk, check-update]
    runs-on: ubuntu-latest
    env:
      SONGS: ./base/assets/songs
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ./base/assets/songs/
          !./base/assets/songs/*/
        key: ${{ runner.os }}-my_file
    - uses: pnpm/action-setup@v2
      with:
        version: 7.14.2
    - uses: actions/setup-node@v3
      with:
        node-version: '16.15'
        cache: 'pnpm'
    - run: pnpm i
    - run: |
        RESULT=$(node ./js/check-edit.js ${{ env.SONGS }}/packlist)
        echo $RESULT
        echo "RESULT=$RESULT" >> $GITHUB_ENV
    - if: ${{ env.RESULT }} == 'false'
      uses: jtmullen/mediawiki-edit-action@v0
      with:
        wiki_text_path: "${{ env.SONGS }}/packlist"
        edit_summary: "Append Latest Update to File.txt"
        page_name: "User:盐棋/Sandbox2"
        api_url: "https://wiki.arcaea.cn/api.php"
        username: "${{ secrets.WIKI_USERNAME }}"
        password: ${{ secrets.WIKI_PASSWORD }}
        append: true
        minor: true