name: try

on:
  workflow_dispatch:

jobs:
  download-apk:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install -y aria2
    - run: aria2c https://static-bin.lowiro.com/serve/arcaea_4.1.3c.apk?token=3Ad7D3EXvx7K5l4ZzS9Vc5sv8LxfKqEj7D7bBuYLXUoKQS1LNpKRdtwhNcQPNjmu9 -j 32 -c -o base.apk
    - run: unzip ./base.apk -d ./base
    - uses: actions/cache@v3
      with:
        path: |
          !./base/assets/songs/*
          ./base/assets/songs/
        key: ${{ runner.os }}-my_file
  edit-wikipage:
    needs: download-apk
    runs-on: ubuntu-latest
    env:
      SONGS: ./base/assets/songs/
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          ./base/assets/songs/
          !./base/assets/songs/*/
        key: ${{ runner.os }}-my_file
    - run: echo ${{ env.SONGS }}/packlist
    - run: |
        result=$(node ./js/check-edit.js ./base/assets/songs/packlist)
        echo "result=$result" >> $GITHUB_ENV
    - if: env.result == 'false'
      run: cat ./base/assets/songs/packlist