name: try

on:
  workflow_dispatch:

jobs:
  url-inject:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 7.14.2
    - uses: actions/setup-node@v3
      with:
        node-version: '16.15'
        cache: 'pnpm'
    - run: pnpm i
    - env:
        URL: https://static-bin.lowiro.com/serve/arcaea_4.1.3c.apk?token=3Ad7D3EXvx7K5l4ZzS9Vc5sv8LxfKqEj7D7bBuYLXUoKQS1LNpKRdtwhNcQPNjmu9
      run: echo "URL=$URL" >> $GITHUB_ENV
  download-apk:
    needs: url-inject
    runs-on: ubuntu-latest
    env:
      URL: ${{env.URL}}
    steps:
    - run: sudo apt-get install -y aria2
    - run: aria2c $URL -j 32 -c -o base.apk
    - run: unzip ./base.apk -d ./base
  edit-wikipage:
    needs: [url-inject, download-apk]
    runs-on: ubuntu-latest
    steps:
    - run: node -v