name: try

on:
  workflow_dispatch:

jobs:
  url-inject:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 7.14.2
    - uses: actions/setup-node@v3
      with:
        node-version: '16.15'
        cache: 'pnpm'
    - run: pnpm i
    - run: |
        read URL VERSION TEXT < <(node ./js/test.js|xargs)
        echo "::set-output url=$URL"
        echo "::set-output version=$VERSION"
        echo "::set-output wikitext=$TEXT"
  download-apk:
    needs: url-inject
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ needs.url-inject.outputs.url }}
        echo ${{ needs.url-inject.outputs.version }}
        echo ${{ needs.url-inject.outputs.wikitext }}
    - run: sudo apt-get install -y aria2
    - run: aria2c ${{ needs.url-inject.outputs.url }} -j 32 -c -o base.apk
    - run: unzip ./base.apk -d ./base
  edit-wikipage:
    needs: [url-inject, download-apk]
    runs-on: ubuntu-latest
    steps:
    - run: node -v
    - run: cat ./base/assets/songs/packlist